- type: type
  template_path: model.tmpl
  output_path: pkg/generated/models/__resource__.go
- type: type
  template_path: model_test.tmpl
  output_path: pkg/generated/models/__resource___test.go
- type: all
  template_path: sql.tmpl
  output_path: tools/init.sql
- type: all
  template_path: sql_cleanup.tmpl
  output_path: tools/cleanup.sql
- type: resource
  template_path: db.tmpl
  output_path: pkg/generated/db/__resource__.go
- type: resource
  template_path: db_test.tmpl
  output_path: pkg/generated/db/__resource___test.go
- type: resource
  template_path: api.tmpl
  output_path: pkg/generated/api/__resource__.go
- type: all
  template_path: api_registry.tmpl
  output_path: pkg/generated/api/api_registry.go
- type: all
  template_path: db_test_main.tmpl
  output_path: pkg/generated/db/main_test.go